"""adiciona tabela relatorios

Revision ID: 58d42cc2789d
Revises: 580b44b1c534
Create Date: 2026-08-08 12:51:31.886337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58d42cc2789d'
down_revision: Union[str, Sequence[str], None] = '580b44b1c534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatorios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('automatico_semanal', 'automatico_mensal', name='tipo_relatorio'), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('dados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatorios')
    # ### end Alembic commands ###
    # Mesmo caso da migração inicial: o Alembic não remove tipos ENUM
    # nativos do Postgres ao dar drop na tabela que os usa.
    sa.Enum(name='tipo_relatorio').drop(op.get_bind(), checkfirst=True)
